version: "3.9"

services:
  api:
    build: ./backend
    container_name: carmarket
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres       # Connects to the 'postgres' service
      DB_USER: postgres
      DB_PASS: youssef
      DB_NAME: CarMarket
      DB_PORT: 5432
      JWT_TOKEN: 0k0CWeBgTqAf338qOrRcybdvdIfcyCJeMCsouVYo2CFLgKoa9HrQVbaVvhYgrsIU
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: pnpm start

  postgres:
    image: postgres:16
    container_name: carmarket_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: youssef
      POSTGRES_DB: CarMarket
    ports:
      - "54321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
